# Generated by Django 3.1.3 on 2020-11-28 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201124_1534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformownership',
            name='modify_access',
        ),
        migrations.RemoveField(
            model_name='platformownership',
            name='view_access',
        ),
        migrations.RemoveField(
            model_name='projectownership',
            name='modify_access',
        ),
        migrations.RemoveField(
            model_name='projectownership',
            name='platform_create_access',
        ),
        migrations.RemoveField(
            model_name='projectownership',
            name='view_access',
        ),
        migrations.RemoveField(
            model_name='user',
            name='project_create_access',
        ),
        migrations.AddField(
            model_name='platformownership',
            name='access_type',
            field=models.CharField(choices=[('V', 'View'), ('M', 'Modify')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='projectownership',
            name='access_type',
            field=models.CharField(choices=[('V', 'View'), ('M', 'Modify')], default='V', max_length=1),
        ),
        migrations.AddField(
            model_name='projectownership',
            name='create_access',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='platformownership',
            name='delete_access',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='projectownership',
            name='delete_access',
            field=models.BooleanField(),
        ),
    ]
