# Generated by Django 3.0.2 on 2020-11-28 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20201128_1239'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platformownership',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='projectownership',
            name='access_type',
        ),
        migrations.RemoveField(
            model_name='projectownership',
            name='create_access',
        ),
        migrations.AddField(
            model_name='platformownership',
            name='modify_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformownership',
            name='view_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectownership',
            name='modify_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectownership',
            name='platform_create_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectownership',
            name='view_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='project_create_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='platformownership',
            name='delete_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='projectownership',
            name='delete_access',
            field=models.BooleanField(default=False),
        ),
    ]
