# Generated by Django 3.0.2 on 2020-11-28 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20201128_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_manned_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.PlatformMannedStatus', verbose_name='[ILOF-63] platform manned status'),
        ),
    ]
