# Generated by Django 3.1.4 on 2020-12-03 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20201203_0952'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='deckelevationwaveindeck',
            name='deck_elevation_wave_in_deck_check',
        ),
    ]
