# Generated by Django 3.1.4 on 2020-12-03 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20201203_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='cellar_deck_height',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, verbose_name='[ILOF-48] cellar deck height (m)'),
        ),
    ]
