# Generated by Django 3.1.4 on 2020-12-03 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20201203_1141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='crest_height_factor',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='[ILOF-52] crest height factor'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='highest_astronomical_tide',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, verbose_name='[ILOF-51] highest astronomical height (m)'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='maximum_wave_height_10000_years',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, verbose_name='[ILOF-49] maximum wave height (m) - 10,000 years'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='maximum_wave_height_100_years',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, verbose_name='[ILOF-49] maximum wave height (m) - 100 years'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='maximum_wave_height_10_years',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, verbose_name='[ILOF-49] maximum wave height (m) - 10 years'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='storm_surge_10000_years',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, verbose_name='[ILOF-50] storm surge (m) - 10,000 years'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='storm_surge_100_years',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, verbose_name='[ILOF-50] storm surge (m) - 100 years'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='storm_surge_10_years',
            field=models.DecimalField(blank=True, decimal_places=5, default=0, max_digits=10, null=True, verbose_name='[ILOF-50] storm surge (m) - 10 years'),
        ),
    ]
