# Generated by Django 3.1.4 on 2020-12-07 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20201206_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scopeofsurvey',
            name='wallut_scope',
        ),
    ]
