# Generated by Django 3.1.4 on 2020-12-07 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_remove_scopeofsurvey_wallut_scope'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='floodedmember',
            name='flooded_member_check',
        ),
        migrations.AlterField(
            model_name='floodedmember',
            name='number_of_flooded_members_in_last_inspection',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='[ILOF-36] number of flooded members in last inspection'),
        ),
        migrations.AlterField(
            model_name='floodedmember',
            name='number_of_previous_inspection_flooded_members',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='[ILOF-39] number of previous inspection flooded members'),
        ),
    ]
