# Generated by Django 3.1.4 on 2020-12-07 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_auto_20201207_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrosion',
            name='average_anode_depletion_from_survey',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='[ILOF-25] average anode depletion from survey (%)'),
        ),
        migrations.AlterField(
            model_name='corrosion',
            name='average_anode_potential_from_survey',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='[ILOF-27] average anode potential from survey (mV)'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='cellar_deck_height',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-48] cellar deck height (m)'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='highest_astronomical_tide',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-51] highest astronomical height (m)'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='maximum_wave_height_10000_years',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-49] maximum wave height (m) - 10,000 years'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='maximum_wave_height_100_years',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-49] maximum wave height (m) - 100 years'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='maximum_wave_height_10_years',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-49] maximum wave height (m) - 10 years'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='storm_surge_10000_years',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-50] storm surge (m) - 10,000 years'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='storm_surge_100_years',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-50] storm surge (m) - 100 years'),
        ),
        migrations.AlterField(
            model_name='deckelevationwaveindeck',
            name='storm_surge_10_years',
            field=models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-50] storm surge (m) - 10 years'),
        ),
        migrations.AlterField(
            model_name='deckload',
            name='increase_in_topsides_load',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='[ILOF-46] increase in topsides load (%)'),
        ),
        migrations.AlterField(
            model_name='economicimpactconsequence',
            name='daily_gas_production',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='[ILOF-70] daily gas production (mscf)'),
        ),
        migrations.AlterField(
            model_name='economicimpactconsequence',
            name='discount_date_for_interrupted_production',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='[ILOF-72] discount rate for interrupted production (%)'),
        ),
        migrations.AlterField(
            model_name='economicimpactconsequence',
            name='fraction_of_remaining_production_loss',
            field=models.DecimalField(decimal_places=3, default=100, max_digits=10, verbose_name='[ILOF-73] fraction of remaining production loss (%)'),
        ),
        migrations.AlterField(
            model_name='economicimpactconsequence',
            name='gas_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='[ILOF-71] gas price ($/mscf)'),
        ),
        migrations.AlterField(
            model_name='economicimpactconsequence',
            name='platform_replacement_cost',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='[ILOF-74] platform replacement cost (usd)'),
        ),
        migrations.AlterField(
            model_name='environmentalconsequence',
            name='estimated_fraction_of_oil_production_loss_due_to_leakage',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-66] estimated fraction of oil production loss due to leakage (%)'),
        ),
        migrations.AlterField(
            model_name='environmentalconsequence',
            name='fixed_cost_for_spill_cleanup',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-67] fixed cost for spill clean-up ($)'),
        ),
        migrations.AlterField(
            model_name='environmentalconsequence',
            name='oil_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-69] oil price ($/bbl)'),
        ),
        migrations.AlterField(
            model_name='environmentalconsequence',
            name='variable_cost_for_spill_cleanup',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, null=True, verbose_name='[ILOF-68] variable cost for spill clean-up ($/bbl)'),
        ),
        migrations.AlterField(
            model_name='fatigueload',
            name='water_depth',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='[ILOF-59] water depth (m)'),
        ),
        migrations.AlterField(
            model_name='marinegrowth',
            name='marine_growth_depths_from_el',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='[ILOF-29] marine growth depths'),
        ),
        migrations.AlterField(
            model_name='marinegrowth',
            name='marine_growth_depths_to_el',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='[ILOF-29] marine growth depths'),
        ),
        migrations.AlterField(
            model_name='marinegrowth',
            name='marine_growth_design_thickness',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='[ILOF-31] marine growth design thickness'),
        ),
        migrations.AlterField(
            model_name='marinegrowth',
            name='marine_growth_inspected_thickness',
            field=models.DecimalField(decimal_places=3, max_digits=10, verbose_name='[ILOF-30] marine growth inspected thickness'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='deck_weight',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='deck weight (mt)'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='distance_to_shipping_lane',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='distance to shipping lane (Km)'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='distance_to_shore',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='distance to shore (Km)'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='pile_penetration_depth',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='pile penetration depth (m)'),
        ),
        migrations.AlterField(
            model_name='reservestrengthratioscore',
            name='reserve_strength_ratio',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='[ILOF-61] reserve strength ratio (rsr)'),
        ),
        migrations.AlterField(
            model_name='scour',
            name='design_scour_depth',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, verbose_name='[ILOF-32] design scour depth (m)'),
        ),
        migrations.AlterField(
            model_name='scour',
            name='measured_scour_depth_during_inspection',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True, verbose_name='[ILOF-34] measured scoured depth during inspection (m)'),
        ),
    ]
