# Generated by Django 3.1.4 on 2020-12-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20201207_0611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otherdetail',
            name='corrosion_survey',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otherdetail',
            name='debris_clearance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otherdetail',
            name='manode_confirmation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otherdetail',
            name='marine_growth_cleaning',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otherdetail',
            name='other',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otherdetail',
            name='scour_repair',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='otherdetail',
            name='weld_monitoring',
            field=models.BooleanField(default=False),
        ),
    ]
