# Generated by Django 3.1.4 on 2020-12-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20201207_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lastinspection',
            name='last_underwater_inspection_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='[ILOF-11] last underwater inspection date'),
        ),
    ]
