# Generated by Django 3.1.4 on 2021-01-06 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20201208_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environmentalconsequence',
            name='platform_type',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.platformtype', verbose_name='[ILOF-64] platform type'),
        ),
        migrations.AlterField(
            model_name='platform',
            name='platform_manned_status',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.platformmannedstatus', verbose_name='[ILOF-63] platform manned status'),
        ),
    ]
