# Generated by Django 3.1.4 on 2021-01-08 07:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20210106_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='platform_manned_status',
            field=models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='core.platformmannedstatus', verbose_name='[ILOF-63] platform manned status'),
        ),
    ]
